name: tropycal
channels:
  - conda-forge
dependencies:
  - matplotlib >= 2.2.2
  - numpy >= 1.14.3
  - scipy >= 1.1.0
  - pandas >= 0.23.0
  - xarray >= 0.10.7
  - networkx >= 2.0.0
  - pyshp >= 2.1
  - cartopy >= 0.17.0
  - tropycal
  - wget
